name: facundobustos
favicon: null
layout_spectrum: 0.4549394026398659
typography_spectrum: 0.37649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111113'
    - '#eff0f2'
    - '#b9bdc2'
    - '#847f80'
    - '#805036'
  brandStrength: 0.6997721469961107
  lightness: 0.9250148215796798
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
