name: facundobustos
favicon: null
layout_spectrum: 0.9245
typography_spectrum: 0.37649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#626262'
    - '#fcfcfc'
    - '#262626'
    - '#cecece'
  brandStrength: 0.6997721469961107
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
